const job_roles = {'Assessor': 'The Assessor is responsible for conducting assessments which measure learner competence and development and managing the award of certifications and accreditations. He/She facilitates  data collection and analysis, using this to measure learner competence and development and establish overall trends and performance gaps. He also provides inputs on the overall effectiveness of the curriculum to facilitate continuous improvement.\n\nHe is analytical and meticulous in nature, with a strong focus on excellence. He maintains impartiality and is able to adapt to different environments and deadlines.\n\nHe typically works in learning venues and may also work from different client sites. He regularly interacts with digital systems.',
 'Courseware Developer': 'The Courseware Developer conducts research and develops learning materials. He/She develops courseware materials based on curriculum objectives and assessment of learning needs. He also develops the learner user experience journey analysing the appropriate learning delivery modes as well as identifying opportunities to integrate learning technology and systems. He designs assessment processes, manages accreditation and certification processes and identifies opportunities to enhance curriculum effectiveness. \n\nHe is creative, analytical and aims to drive innovation. He is detail-oriented and has excellent critical thinking and research skills. He is resourceful and collaborates effectively with stakeholders across the organisation. \n\nHe typically works in an office environment and regularly interacts with digital systems.',
 'Curriculum Lead': 'The Curriculum Lead oversees the development of curriculum and courseware materials to drive learning experience excellence. He/She is responsible for designing curriculum \nspecifications and overseeing the development of courseware materials. He evaluates overall curriculum effectiveness and recommends improvement areas. He leads teams that are responsible for the creation of learning curriculum, services and technology. He also drives innovation and research by prioritising research areas and recommending potential \nresearch applications. He manages and fosters relationships with stakeholders and vendors to ensure seamless integration and implementation of learning curriculum, systems and technologies. \n\nHe is forward-thinking, creative and champions innovation. He is able to communicate clearly and effectively allocates resources and manages workloads across teams. He is able to prioritise and evaluate short and long-term outcomes and needs. He manages stakeholders across the organisation and fosters a collaborative team environment. \n\nHe typically works in an office environment and regularly interacts with digital systems.',
 'Learning Consultant / Learning Solutionist': 'The Learning Consultant/Learning Solutionist provides consultancy and advisory services on learning solutions and interventions. He/She liaises and collaborates with various stakeholders to understand critical requirements and objectives so as to diagnose workplace performance gaps and evaluate learning opportunities. He then designs and implements bespoke learning solutions and interventions to drive business results, workplace performance improvement and behaviour change. He evaluates the impact and effectiveness of \nlearning solutions and interventions, and develops long-term implementation plans. He manages and fosters relationships with stakeholders and vendors to ensure effective, \nsustainable implementation. \n\nHe is creative, analytical and adept at forming connections between performance gaps and learning solutions and interventions. He enjoys solving problems and has excellent critical thinking skills. He is highly adaptable to different environments and has excellent interpersonal, change management and communication skills. He has strong business acumen and is results oriented. He manages multiple stakeholders and builds strong relationships and robust business networks. \n\nHe works in multiple different environments, including different learning venues and client sites, and regularly interacts with digital systems.',
 'Learning Facilitator': 'The Learning Facilitator delivers learning products and services in a variety of environments, using multiple learning delivery modes and methods. He/She assesses learning needs and adapts the facilitation approach to reflect desired learning outcomes and learner needs. He is responsible for knowledge and skills transfer by delivering learning content, facilitating group discussions and responding to queries. He drives learner development and commitment to continuous learning by actively providing feedback and learner support. He evaluates curriculum effectiveness and recommends improvement areas by collecting learner feedback as well as analysing learning delivery approaches and materials. \n\nHe is a strong communicator who builds trusted relationships and creates a cooperative and engaging learning environment. He is adaptable and adept at managing multiple stakeholders. \n\nHe works in multiple different environments, including different learning venues and client sites, and regularly interacts with digital systems.',
 'Learning Technology Designer': 'The Learning Technology Designer develops learning technology prototypes to identify potential integration opportunities. He/She assesses learning needs to effectively integrate learning technology innovations which enhance the learner experience. He drives innovation and research by identifying emerging technology applications and develops roadmaps for technology implementation. He analyses data to evaluate the effectiveness of learning technology and systems, identifying improvement opportunities. \n\nHe is analytical and creative. He is collaborative, a strong communicator and effective at managing stakeholders across the organisation. He has a digital mindset and is passionate about driving digital adoption and integration. \n\nHe typically works in an office environment and is at ease operating with learning technologies.',
 'Centre Director / Head of Institute': "The Centre Director/Head of Institute sets the overall learning direction for the organisation, formulates strategic goals and drives organisational growth. He/She assesses the industry \nlandscape to identify new business opportunities and drive the continual development of the organisation's learning products and services portfolio. He champions the organisations service excellence aspirations and fosters strategic relationships with stakeholders. He is accountable for the success of the organisation and is responsible for driving the \norganisations financial, innovation and productivity strategies. He has a strong understanding of market and industry developments, including research developments and technology innovations. \n\nHe is an inspirational leader with a forward-thinking mindset and a deep passion for learning and development. He establishes and communicates a clear vision, and is highly skilled in influencing and engaging stakeholders to secure their buy-in and support. He has strong business acumen and is able to make calculated-risk decisions, performing effectively in a complex and difficult environment. \n\nHe frequently works outside of the office, attends industry events and client meetings to develop networks and build strong business relationships.",
 'Business Development Manager': "The Business Development Manager drives the organisation's marketing and sales strategies, leading to improved market position and business growth. He/She assesses the \nindustry landscape to drives sales excellence by prospecting new sales leads and contracts. He leads the development of marketing objectives, strategies and execution plans. He \nidentifies new business opportunities, communicates new product developments to prospective clients and negotiates business deals. He drives financial performance by analysing return on investment and leading the identification and solicitation of funding opportunities. He manages vendors and key client relationships so as to establish long-term stakeholder business collaborations. \n\nHe possesses strong business acumen and is adept at understanding client needs and market dynamics. He builds effective stakeholder relationships and thrives in a competitive \nenvironment. He is able to communicate complex messages to a range of audiences. He has a growth mindset and is passionate about innovation and building an industry presence.\n \nHe may be required to work within and outside of the office environment, and often interacts with digital systems. He often attends industry events and meets clients so as to develop networks and strong business relationships.",
 'Learning and Operations Manager': "The Learning and Operations Manager manages the organisation's learning products and services and operational processes. He/She sets the overall learning calendar, manages resources and oversees the administration and execution of products and services. He manages the portfolio of products and services, monitoring performance and identifying \nopportunities for improvement. He conducts ongoing assessments of products and services, considering profitability, take-up rates, learning delivery and participant feedback. He is responsible for managing vendors and for the recruitment, management and development of the personnel involved in learning delivery, including adjunct professionals. He drives financial performance and implements and maintains processes which drive operational excellence. \n\nHe is collaborative and adept at managing stakeholder relationships and developing a positive team dynamic. He possesses strong communication skills, and is an enabler to \nmotivate and empathise with employees while enforcing high standards of service in the organisation. He has robust operational intelligence and is astute at identifying performance issues. \n\nHe works in an office environment, interacts regularly with digital systems and stakeholders, and can also be required to attend specific learning venues or client sites.",
 'Learning Quality Manager': 'The Learning Quality Manager is responsible for managing quality assurance activities and accreditation processes across the organisation. He/She designs quality assurance policies and systems and oversees implementation across the organisation. He evaluates adherence to quality assurance policies and systems, and develops accreditation and certification management processes. He assesses learning products and services against internal and external accreditation standards to determine accreditation and certification eligibility. He drives operational excellence across the organisation, implements processes which aim to a deliver consistent approach and identifies opportunities for improvement. He manages and fosters relationships with stakeholders and vendors to ensure compliance with organisational quality policies and systems. \n\nHe leads by example and is passionate about driving operational excellence and championing quality standards across the organisation. He is diplomatic and highly skilled at engaging with others, thereby facilitating the creation of an organisational culture which is cooperative and strives for continuous development and excellence. \n\nHe works in an office environment, interacts regularly with digital systems, and can also be required to attend specific learning venues or client sites.',
 'Learning Support Executive': "The Learning Support Executive performs routine learning administration-related activities. He/She facilitates the coordination of the organisation's products and services by liaising with vendors and relevant stakeholders, managing learner records and updating learning management systems. He consolidates the learning data collected and conducts data analysis for compilation of data reporting. He assists with the creation of the desired learning environment and the management of logistics and equipment. He assists and supports business development activities by executing marketing activities. \n\nHe enjoys working in a team environment and interacts proactively with various internal and external stakeholders. He is eager to serve others, has excellent organisation and administrative skills and can adapt to using various systems and forms of technology. \n\nHe typically works in an office environment, often interacts with digital systems, but can also be required to provide support at specific learning venues or client sites.",
 'Learning Systems Manager': 'The Learning Systems Manager is responsible for the management of learning technology and systems. He/She plans and oversees learning technology and system integration, implementation, improvement and maintenance to ensure coherence across the organisation. He manages projects related to systems installations and configurations as well as monitoring and maintenance. He maximises service uptime, system backups, and manages service licensing and security standards for learning technology platforms and systems. He aims to drive digital innovation and data measurement as well as identifying opportunities for technology integration and deployment across the organisation. He designs and implements systems which offer user support/training and responds to user queries. He drives financial performance by managing learning technology and system budgets and \napprovals as well as analysing return on investment. \n\nHe is collaborative and results-oriented, driving systems excellence and innovation across the organisation. He is able to manage multiple projects effectively and build strong stakeholder relationships to anticipate organisational and learning needs. \n\nHe works in an office environment and is at ease in digital environments. He can also be required to attend specific learning venues or client sites to assist with system set-ups.',
 'Product Development Manager': "The Product Development Manager drives the innovation and development of the organisation's products and services to achieve business growth. He/She assesses the industry landscape, reviews existing products and services and prospects new learning offerings to be implemented. He manages the portfolio of products and services by evaluating performance and assessing opportunities for improvement. He drives innovation and leads research on market trends and learning developments to determine opportunities for implementation. He assesses the profitability and viability of developing or adjusting products and services, curriculum, tools and other offerings. He drives sales excellence and manages vendors and key client relationships so as to establish long-term stakeholder business collaborations. \n\nHe is forward thinking and creative, championing innovation across the organisation. He is highly analytical and resourceful, deploying his strong industry and business acumen to maximise opportunities for innovation. He is able to take calculated risks and balance long and short-term priorities. He inspires collaboration across the organisation and is able to manage multiple stakeholders priorities effectively. \n\nHe typically works in an office environment, interacts regularly with digital systems, and attends specific learning venues, client sites or industry events."}


// Populate the Job Role dropdown
function populateJobRole() {
    const jobRoleSelect = document.getElementById('jobRole');
    const jobRoles = Object.keys(job_roles);

    jobRoles.forEach(role => {
        const option = document.createElement('option');
        option.value = role;
        option.textContent = role;
        jobRoleSelect.appendChild(option);
    });
}

// Show Job Role Description based on Job Role selection
function showJobRoleDescription() {
    const jobRole = document.getElementById('jobRole').value;
    const jobRoleDescription = document.getElementById('jobRoleDescription');
    const jobRoleDescriptionTitle = document.getElementById('jobRoleDescriptionTitle')

    if (jobRole && job_roles[jobRole]) {
        jobRoleDescription.textContent = job_roles[jobRole];
        jobRoleDescriptionTitle.textContent = "Job Description"
    } else {
        jobRoleDescription.textContent = 'Description not available.';
    }
}

// Populate Critical Work Function based on Job Role selection
function populateCriticalWorkFunction() {
    const jobRole = document.getElementById('jobRole').value;
    const workFunctionSelect = document.getElementById('workFunction');
    workFunctionSelect.innerHTML = '<option value="">-- Select Critical Work Function --</option>';

    const filteredFunctions = data.filter(item => item['Job Role'] === jobRole);

    const workFunctions = [...new Set(filteredFunctions.map(item => item['Critical Work Function']))];
    workFunctions.forEach(func => {
        const option = document.createElement('option');
        option.value = func;
        option.textContent = func;
        workFunctionSelect.appendChild(option);
    });
}

// Populate Key Tasks based on Critical Work Function selection
function populateKeyTasks() {
    const workFunction = document.getElementById('workFunction').value;
    const keyTasksSelect = document.getElementById('keyTasks');
    keyTasksSelect.innerHTML = '<option value="">-- Select Key Tasks --</option>';

    const filteredTasks = data.filter(item => item['Critical Work Function'] === workFunction);

    const keyTasks = [...new Set(filteredTasks.map(item => item['Key Tasks']))];
    keyTasks.forEach(task => {
        const option = document.createElement('option');
        option.value = task;
        option.textContent = task;
        keyTasksSelect.appendChild(option);
    });
}

// Initialize the Job Role dropdown on page load
window.onload = populateJobRole;
